### ISSUE TITLE
MAGIC

### ISSUE THREAD

**Issue by mjchen-st** [vincentgarin/mppR#7]
Hi,
There are examples for MAGIC in the article, but I did not find usage in the software.
 Can mppr be used in the MAGIC.
“An IBD‑based mixed model approach for QTL mapping in multiparental populations”

**Comment by mjchen-st** [comment]
And can mppr be used in MAGIC + NAM ?

**Comment by vincentgarin** [comment]
Concerning the article “An IBD‑based mixed model approach for QTL mapping in multiparental populations”, they indeed performed comparison with NAM and MAGIC population analysis. They use mppR and their own software to analyze the NAM data but the MAGIC analysis was only performed using their own software.

Concerning the possibility to analyze MAGIC populations using mppR: mppR works with data from collection of crosses with no further intercrossing. Each individual is the product of only two parents. Populations like nested association mapping (NAM), factorial design, diallel, and breeding populations composed of crosses can be analyzed using mppR. However, in populations like MAGIC, the final line are a mosaic or the (4, 8, …) founders lines. mppR is not able to infer the parental origin of the haplotype blocks by the calculation of IBD probabilities. For those type of data, I suggest to have a look to the RABBIT software (Zheng et al. 2014 - Genetics) or the r/qtl2 package.
