### ISSUE TITLE
Components depending on ASReml

### ISSUE THREAD

**Issue by EDVRK** [vincentgarin/mppR#9]
Dear Vincent,

I'm using mppR for multiple environment QTL detection.

I noticed you indicated that "_some of the components that are based on mixed model technology depend on the ASReml-R package and require a license_".

How can I know if I'm using any function that depends on ASRmel ? Are there specific options to avoid ?

Best regards,
Etienne D.

**Comment by vincentgarin** [comment]
This is related to a previous github version.

There is now a version of mppR on CRAN that integrate function for
multi-environment analysis working without asreml.

https://cran.r-project.org/web/packages/mppR/index.html

For further information have a look to the specific vignette

https://cran.r-project.org/web/packages/mppR/vignettes/MPP_ME_QTL_detect.html

Do not hesitate if you have any questions.

Best regards,
Vincent

**Comment by EDVRK** [comment]
Thank you for your response, indeed I read that in the old vignette.
